### ISSUE TITLE
Registration Stopped Working

### ISSUE THREAD

**Issue by AbyssWatcher** [TeamCho/ShelterSearch#23]
Registering a new user with their username, email, and password does not work.  The onClickRegister() method could not be executed.  
- A useful error message is the following: Caused by: java.lang.ClassCastException: com.teamcho.sheltersearch.model.UserType cannot be cast to java.lang.String.  
- The error occurs at line 81 in the RegisterActivity.java file.  
- The error has to do with the changing of the variables stored under Users (which was changed from a UserType enum to a String).

**Comment by luis-gzz** [comment]
Fixed
